### ISSUE TITLE
6.Скрипт create_trans_file.php необходимо запустить на сервере в режиме daemon.

### ISSUE THREAD

**Issue by admin-klient** [cardpr/rkeeper-hook#5]
6.Скрипт create_trans_file.php необходимо запустить на сервере в режиме daemon.

Каким образом данный файл запустить в режиме DAEMON? В свойствах файла прописать \daemon или как? Пункт не ясен.

**Comment by cardpr** [comment]
Данной информации нет в текущей версии документации.
